package com.lingce.cleanguardian

import java.net.HttpURLConnection
import java.net.URL
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import kotlin.math.min

class FileClassifier {
    private val tmpSuffixes = setOf(".tmp", ".temp", ".swp", ".swo", ".bak", ".orig", ".old", ".log")
    private val configNames = setOf(
        "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts",
        "gradle.properties", "package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
        ".gitignore", ".gitattributes", ".editorconfig", ".env", ".env.local", ".env.dev", ".env.prod",
        "dockerfile", "docker-compose.yml", "docker-compose.yaml", ".npmrc", ".nvmrc", ".tool-versions"
    )
    private val aiConfigKeywords = listOf(
        ".cursor", ".cursorrules", ".copilot", ".aider", "continue", ".windsurf", ".roo", ".cline", ".codeium"
    )
    private val aiGarbageKeywords = listOf(
        "generated by chatgpt", "generated by ai", "ai generated", "autogenerated by gpt",
        "todo: implement", "placeholder implementation", "lorem ipsum", "your code here"
    )
    private val knownSourceExtensions = setOf(
        ".java", ".kt", ".kts", ".groovy", ".scala", ".js", ".ts", ".tsx", ".jsx", ".py", ".go", ".rs",
        ".c", ".cc", ".cpp", ".h", ".hpp", ".php", ".rb", ".swift", ".m", ".mm", ".cs", ".vue", ".svelte",
        ".css", ".scss", ".less", ".html", ".md", ".json", ".yaml", ".yml", ".toml", ".xml", ".sql", ".sh",
        ".bash", ".zsh", ".ps1", ".txt", ".properties", ".ini", ".conf", ".cfg"
    )

    fun classify(
        path: Path,
        relativePath: String,
        settings: CleanGuardianSettingsService.State
    ): ClassificationResult {
        val fileName = path.fileName.toString()
        val lowerName = fileName.lowercase()
        val lowerRelativePath = relativePath.lowercase()

        if (isTmpFile(lowerName, lowerRelativePath)) {
            return ClassificationResult(FileCategory.TMP, 0.98, "Temporary file pattern matched")
        }
        if (isProjectConfig(lowerName)) {
            return ClassificationResult(FileCategory.PROJECT_CONFIG, 0.95, "Project configuration file")
        }
        if (isAiConfig(lowerName, lowerRelativePath)) {
            return ClassificationResult(FileCategory.AI_CONFIG, 0.95, "AI tool configuration file")
        }

        val maxSize = settings.maxFileSizeKb.toLong() * 1024L
        val size = runCatching { Files.size(path) }.getOrElse { 0L }
        if (size > maxSize) {
            return ClassificationResult(FileCategory.SKIPPED, 0.0, "File too large: $size bytes")
        }

        if (isLikelyBinary(path)) {
            return ClassificationResult(FileCategory.SKIPPED, 0.0, "Binary file skipped")
        }

        val content = runCatching { Files.readString(path) }.getOrNull()
            ?: return ClassificationResult(FileCategory.SKIPPED, 0.0, "Cannot read as text")
        val lowerContent = content.lowercase()

        if (looksLikeAiGarbage(lowerName, lowerContent)) {
            return ClassificationResult(FileCategory.AI_GARBAGE, 0.9, "AI generated garbage markers found")
        }

        classifyWithAiApi(fileName, relativePath, content, settings)?.let { aiResult ->
            if (aiResult.category != FileCategory.NORMAL && aiResult.confidence >= 0.7) {
                return aiResult
            }
        }

        if (looksSuspicious(lowerName, lowerRelativePath, lowerContent)) {
            return ClassificationResult(FileCategory.SUSPICIOUS, 0.75, "Unexpected/suspicious file pattern")
        }

        return ClassificationResult(FileCategory.NORMAL, 0.6, "No cleanup pattern matched")
    }

    private fun isTmpFile(fileName: String, relativePath: String): Boolean {
        if (tmpSuffixes.any { fileName.endsWith(it) }) return true
        if (fileName.startsWith("~$") || fileName.startsWith(".#")) return true
        if ("/tmp/" in relativePath || "\\tmp\\" in relativePath) return true
        return false
    }

    private fun isProjectConfig(fileName: String): Boolean {
        if (fileName in configNames) return true
        if (fileName.endsWith(".iml")) return true
        if (fileName.startsWith(".env")) return true
        return false
    }

    private fun isAiConfig(fileName: String, relativePath: String): Boolean {
        if (aiConfigKeywords.any { fileName.contains(it) }) return true
        if (aiConfigKeywords.any { relativePath.contains("/$it/") }) return true
        return false
    }

    private fun looksLikeAiGarbage(fileName: String, lowerContent: String): Boolean {
        if (fileName.contains("ai_generated") || fileName.contains("chatgpt") || fileName.contains("copilot")) {
            return true
        }
        if (aiGarbageKeywords.any { lowerContent.contains(it) }) return true
        if (lowerContent.contains("this file is generated") && lowerContent.contains("do not edit")) return true
        return false
    }

    private fun looksSuspicious(fileName: String, relativePath: String, lowerContent: String): Boolean {
        if (Regex("^[a-f0-9]{24,}").matches(fileName.substringBefore('.'))) return true
        if (fileName.contains("unknown") || fileName.contains("suspicious")) return true
        val extension = "." + fileName.substringAfterLast('.', "")
        if (extension != "." && extension !in knownSourceExtensions &&
            !relativePath.startsWith(".git/") && !relativePath.contains("/node_modules/")
        ) {
            return true
        }
        if (lowerContent.length in 10..160 && lowerContent.contains("rm -rf")) return true
        return false
    }

    private fun isLikelyBinary(path: Path): Boolean {
        val bytes = runCatching {
            Files.newInputStream(path).use { input ->
                val maxRead = 1024
                val buffer = ByteArray(maxRead)
                val read = input.read(buffer)
                if (read <= 0) ByteArray(0) else buffer.copyOf(read)
            }
        }.getOrElse { ByteArray(0) }
        return bytes.any { it.toInt() == 0 }
    }

    private fun classifyWithAiApi(
        fileName: String,
        relativePath: String,
        content: String,
        settings: CleanGuardianSettingsService.State
    ): ClassificationResult? {
        if (settings.apiBaseUrl.isBlank() || settings.apiKey.isBlank()) return null

        val endpoint = buildEndpoint(settings.apiBaseUrl)
        val prompt = """
            You are a file hygiene classifier.
            Classify this file into one of:
            TMP, PROJECT_CONFIG, AI_CONFIG, AI_GARBAGE, SUSPICIOUS, NORMAL
            Return strict JSON only:
            {"category":"...","confidence":0.0-1.0,"reason":"..."}
            
            file_name: $fileName
            relative_path: $relativePath
            file_content:
            ${content.take(min(6000, content.length))}
        """.trimIndent()

        val requestBody = """
            {
              "model":"${escapeJson(settings.model.ifBlank { "gpt-4o-mini" })}",
              "messages":[{"role":"user","content":"${escapeJson(prompt)}"}],
              "temperature":0.0
            }
        """.trimIndent()

        val connection = (URL(endpoint).openConnection() as HttpURLConnection).apply {
            requestMethod = "POST"
            connectTimeout = 8000
            readTimeout = 10000
            doOutput = true
            setRequestProperty("Content-Type", "application/json")
            setRequestProperty("Authorization", "Bearer ${settings.apiKey.trim()}")
        }

        return runCatching {
            connection.outputStream.use { output ->
                output.write(requestBody.toByteArray(StandardCharsets.UTF_8))
            }
            val code = connection.responseCode
            val body = (if (code in 200..299) connection.inputStream else connection.errorStream)
                ?.bufferedReader(StandardCharsets.UTF_8)
                ?.use { it.readText() }
                .orEmpty()
            if (code !in 200..299 || body.isBlank()) return null
            val contentField = extractFirstJsonStringField(body, "content") ?: return null
            parseModelResult(contentField)
        }.getOrNull()
    }

    private fun buildEndpoint(baseUrl: String): String {
        val trimmed = baseUrl.trim().trimEnd('/')
        return if (trimmed.endsWith("/chat/completions")) trimmed else "$trimmed/chat/completions"
    }

    private fun parseModelResult(modelText: String): ClassificationResult? {
        val categoryRaw = extractRegex(modelText, "\"category\"\\s*:\\s*\"([A-Z_]+)\"") ?: return null
        val confidenceRaw = extractRegex(modelText, "\"confidence\"\\s*:\\s*([0-9]*\\.?[0-9]+)") ?: "0.6"
        val reason = extractRegex(modelText, "\"reason\"\\s*:\\s*\"([^\"]*)\"") ?: "Model classification"

        val category = runCatching { FileCategory.valueOf(categoryRaw) }.getOrNull() ?: return null
        val confidence = confidenceRaw.toDoubleOrNull() ?: 0.6
        return ClassificationResult(category, confidence.coerceIn(0.0, 1.0), reason)
    }

    private fun extractFirstJsonStringField(source: String, fieldName: String): String? {
        val regex = Regex("\"$fieldName\"\\s*:\\s*\"((?:\\\\.|[^\"\\\\])*)\"")
        val raw = regex.find(source)?.groupValues?.get(1) ?: return null
        return unescapeJson(raw)
    }

    private fun extractRegex(source: String, pattern: String): String? {
        return Regex(pattern).find(source)?.groupValues?.getOrNull(1)
    }

    private fun escapeJson(input: String): String {
        return input
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
    }

    private fun unescapeJson(input: String): String {
        return input
            .replace("\\n", "\n")
            .replace("\\r", "\r")
            .replace("\\t", "\t")
            .replace("\\\"", "\"")
            .replace("\\\\", "\\")
    }
}
