package com.lingce.cleaner;

import com.intellij.notification.Notification;
import com.intellij.notification.NotificationAction;
import com.intellij.notification.NotificationGroupManager;
import com.intellij.notification.NotificationType;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.command.WriteCommandAction;
import com.intellij.openapi.components.Service;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VfsUtil;
import com.intellij.openapi.vfs.VfsUtilCore;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.util.concurrency.AppExecutorUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

@Service(Service.Level.PROJECT)
public final class AiCleanerService {
    private static final Logger LOG = Logger.getInstance(AiCleanerService.class);
    private static final int MAX_FILES_PER_SCAN = 4_000;
    private static final String NOTIFICATION_GROUP = "LingCe AI Cleaner";
    private static final DateTimeFormatter QUARANTINE_FORMAT = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss");

    private static final Set<String> SKIPPED_DIRECTORIES = Set.of(
        ".git", "node_modules", "vendor", "dist", "build", "out", "target", ".ai-cleaner"
    );
    private static final Set<String> TEMP_DIRECTORY_NAMES = Set.of(
        "tmp", "temp", ".tmp", ".temp", "__pycache__", ".pytest_cache", ".cache", ".parcel-cache", ".turbo"
    );
    private static final Set<String> CONFIG_DIRECTORY_NAMES = Set.of(
        ".idea", ".vscode", ".settings", ".cursor", ".continue", ".claude"
    );
    private static final Pattern TEMP_FILE_PATTERN = Pattern.compile(
        "(?i)(^~\\$.*|.*(~|\\.tmp|\\.temp|\\.bak|\\.swp|\\.swo|\\.orig|\\.rej|\\.part|\\.crdownload|\\.download|\\.old)$)"
    );
    private static final Pattern CONFIG_FILE_PATTERN = Pattern.compile(
        "(?i)(.*\\.iml|.*\\.ipr|.*\\.iws|\\.classpath|\\.project|\\.factorypath|.*\\.code-workspace|\\.cursorrules|\\.cursorignore|\\.mcp\\.json|\\.aider.*|CLAUDE\\.md|GEMINI\\.md|AGENTS\\.md)"
    );
    private static final Pattern DISPOSABLE_AI_PATH_PATTERN = Pattern.compile(
        "(?i).*(ai[-_ ]?(draft|scratch|output|tmp|temp|generated|note)|chatgpt[-_ ]?(draft|output|tmp)?|claude[-_ ]?(draft|output|tmp)?|copilot[-_ ]?(draft|output|tmp)?|cursor[-_ ]?(scratch|tmp|output)|prompt[-_ ]?(result|output|draft)).*"
    );
    private static final List<String> AI_CONTENT_MARKERS = List.of(
        "generated by chatgpt",
        "generated by claude",
        "generated by cursor",
        "ai-generated",
        "ai generated",
        "created by an ai",
        "created by ai",
        "llm generated",
        "prompt:",
        "as an ai language model"
    );

    private final Project project;
    private final AiRemoteClassifier remoteClassifier = new AiRemoteClassifier();
    private final Set<String> pendingPaths = java.util.Collections.synchronizedSet(new HashSet<>());

    public AiCleanerService(Project project) {
        this.project = project;
    }

    public void scanProject() {
        AppExecutorUtil.getAppExecutorService().execute(() -> {
            AiCleanerSettings.StateData settings = AiCleanerSettings.getInstance().getState();
            if (!settings.enabled) {
                return;
            }

            VirtualFile baseDir = getBaseDir();
            if (baseDir == null) {
                return;
            }

            AtomicInteger visited = new AtomicInteger();
            scanRecursively(baseDir, settings, visited);
        });
    }

    public void inspectNewFile(@NotNull VirtualFile file) {
        String path = file.getPath();
        if (!pendingPaths.add(path)) {
            return;
        }

        AppExecutorUtil.getAppExecutorService().execute(() -> {
            try {
                AiCleanerSettings.StateData settings = AiCleanerSettings.getInstance().getState();
                if (settings.enabled && file.isValid() && isInsideProject(file)) {
                    inspectAndAct(file, settings);
                }
            } finally {
                pendingPaths.remove(path);
            }
        });
    }

    private void scanRecursively(VirtualFile file, AiCleanerSettings.StateData settings, AtomicInteger visited) {
        if (!file.isValid() || visited.incrementAndGet() > MAX_FILES_PER_SCAN) {
            return;
        }

        String name = file.getName();
        if (file.isDirectory()) {
            if (isConfigurationDirectory(name) || isTemporaryDirectory(name)) {
                inspectAndAct(file, settings);
                return;
            }
            if (SKIPPED_DIRECTORIES.contains(name)) {
                return;
            }
            for (VirtualFile child : file.getChildren()) {
                scanRecursively(child, settings, visited);
            }
            return;
        }

        inspectAndAct(file, settings);
    }

    private void inspectAndAct(VirtualFile file, AiCleanerSettings.StateData settings) {
        FileClassification classification = classify(file, settings);
        switch (classification.category()) {
            case TEMPORARY -> {
                if (settings.autoDeleteTempFiles) {
                    deleteFile(file, "Deleted temporary file: " + classification.reason());
                }
            }
            case CONFIGURATION -> {
                if (settings.autoIgnoreConfigFiles) {
                    addIgnoreRule(file, classification.reason());
                }
            }
            case DISPOSABLE_AI -> {
                if (settings.autoDeleteDisposableAiFiles) {
                    deleteFile(file, "Deleted disposable AI-generated file: " + classification.reason());
                } else {
                    notifySuspicious(file, classification);
                }
            }
            case SUSPICIOUS_AI, UNKNOWN -> notifySuspicious(file, classification);
            case SAFE -> {
            }
        }
    }

    private FileClassification classify(VirtualFile file, AiCleanerSettings.StateData settings) {
        String relativePath = relativePath(file);
        String fileName = file.getName();

        if (isTemporary(file, relativePath, settings)) {
            return new FileClassification(FileClassification.Category.TEMPORARY, "matched temporary file rule");
        }

        if (isConfiguration(file, relativePath)) {
            return new FileClassification(FileClassification.Category.CONFIGURATION, "matched project or AI configuration rule");
        }

        if (file.isDirectory()) {
            return new FileClassification(FileClassification.Category.SAFE, "directory has no cleanup signal");
        }

        String content = readTextContent(file, settings);
        boolean pathLooksDisposableAi = DISPOSABLE_AI_PATH_PATTERN.matcher(relativePath).matches()
            || DISPOSABLE_AI_PATH_PATTERN.matcher(fileName).matches();
        boolean contentHasAiMarker = containsAiMarker(content);

        if (pathLooksDisposableAi && (contentHasAiMarker || isTextualScratchFile(fileName))) {
            return new FileClassification(FileClassification.Category.DISPOSABLE_AI, "path and content look like disposable AI output");
        }

        if (contentHasAiMarker) {
            if (pathLooksDisposableAi) {
                return new FileClassification(FileClassification.Category.DISPOSABLE_AI, "AI marker in disposable-looking file");
            }
            return new FileClassification(FileClassification.Category.SUSPICIOUS_AI, "content contains AI generation marker");
        }

        Optional<RemoteClassification> remote = shouldUseRemoteClassifier(relativePath, fileName, content)
            ? remoteClassifier.classify(relativePath, content, settings)
            : Optional.empty();
        if (remote.isPresent() && remote.get().aiGenerated()) {
            RemoteClassification result = remote.get();
            if (result.disposable() || pathLooksDisposableAi) {
                return new FileClassification(FileClassification.Category.DISPOSABLE_AI, result.reason());
            }
            return new FileClassification(FileClassification.Category.SUSPICIOUS_AI, result.reason());
        }

        if (pathLooksDisposableAi) {
            return new FileClassification(FileClassification.Category.SUSPICIOUS_AI, "path looks like AI assistant output");
        }

        return new FileClassification(FileClassification.Category.SAFE, "no cleanup signal");
    }

    private boolean shouldUseRemoteClassifier(String relativePath, String fileName, String content) {
        if (AiCleanerSettings.isBlank(content)) {
            return false;
        }

        String lowerPath = relativePath.toLowerCase(Locale.ROOT);
        String lowerName = fileName.toLowerCase(Locale.ROOT);
        return DISPOSABLE_AI_PATH_PATTERN.matcher(relativePath).matches()
            || lowerPath.contains("prompt")
            || lowerPath.contains("generated")
            || lowerPath.contains("scratch")
            || lowerPath.contains("draft")
            || lowerName.contains("ai")
            || lowerName.contains("llm");
    }

    private boolean isTemporary(VirtualFile file, String relativePath, AiCleanerSettings.StateData settings) {
        if (file.isDirectory() && isTemporaryDirectory(file.getName())) {
            return true;
        }
        if (!file.isDirectory() && TEMP_FILE_PATTERN.matcher(file.getName()).matches()) {
            return true;
        }
        for (Pattern pattern : customPatterns(settings.customTempPatterns)) {
            if (pattern.matcher(relativePath).matches() || pattern.matcher(file.getName()).matches()) {
                return true;
            }
        }
        return false;
    }

    private boolean isConfiguration(VirtualFile file, String relativePath) {
        if (file.isDirectory() && isConfigurationDirectory(file.getName())) {
            return true;
        }
        return !file.isDirectory() && CONFIG_FILE_PATTERN.matcher(file.getName()).matches()
            || relativePath.equals(".github/copilot-instructions.md")
            || relativePath.startsWith(".github/prompts/");
    }

    private boolean isConfigurationDirectory(String name) {
        return CONFIG_DIRECTORY_NAMES.contains(name);
    }

    private boolean isTemporaryDirectory(String name) {
        return TEMP_DIRECTORY_NAMES.contains(name.toLowerCase(Locale.ROOT));
    }

    private boolean containsAiMarker(String content) {
        if (AiCleanerSettings.isBlank(content)) {
            return false;
        }
        String lower = content.toLowerCase(Locale.ROOT);
        for (String marker : AI_CONTENT_MARKERS) {
            if (lower.contains(marker)) {
                return true;
            }
        }
        return false;
    }

    private boolean isTextualScratchFile(String fileName) {
        String lower = fileName.toLowerCase(Locale.ROOT);
        return lower.endsWith(".md")
            || lower.endsWith(".txt")
            || lower.endsWith(".json")
            || lower.endsWith(".yaml")
            || lower.endsWith(".yml");
    }

    private List<Pattern> customPatterns(String patterns) {
        if (AiCleanerSettings.isBlank(patterns)) {
            return List.of();
        }
        return patterns.lines()
            .map(String::trim)
            .filter(line -> !line.isEmpty())
            .map(line -> {
                try {
                    return Pattern.compile(line);
                } catch (PatternSyntaxException e) {
                    LOG.warn("Invalid AI cleaner temp pattern: " + line, e);
                    return null;
                }
            })
            .filter(pattern -> pattern != null)
            .toList();
    }

    private String readTextContent(VirtualFile file, AiCleanerSettings.StateData settings) {
        long maxBytes = Math.max(1, settings.maxScanFileSizeKb) * 1024L;
        if (!file.isValid() || file.isDirectory() || file.getLength() > maxBytes || file.getFileType().isBinary()) {
            return "";
        }

        try {
            byte[] bytes = file.contentsToByteArray(false);
            if (looksBinary(bytes)) {
                return "";
            }
            return new String(bytes, StandardCharsets.UTF_8);
        } catch (IOException e) {
            LOG.warn("Failed to read file for AI cleaner: " + file.getPath(), e);
            return "";
        }
    }

    private boolean looksBinary(byte[] bytes) {
        int limit = Math.min(bytes.length, 4096);
        for (int i = 0; i < limit; i++) {
            if (bytes[i] == 0) {
                return true;
            }
        }
        return false;
    }

    private void addIgnoreRule(VirtualFile file, String reason) {
        Path basePath = getBasePath();
        if (basePath == null) {
            return;
        }

        AiCleanerSettings.StateData settings = AiCleanerSettings.getInstance().getState();
        String ignoreFileName = AiCleanerSettings.isBlank(settings.ignoreFileName) ? ".gitignore" : settings.ignoreFileName.trim();
        String relativePath = relativePath(file);
        String ignoreRule = "/" + relativePath + (file.isDirectory() ? "/" : "");
        Path ignorePath = basePath.resolve(ignoreFileName).normalize();

        AppExecutorUtil.getAppExecutorService().execute(() -> {
            try {
                if (ignorePath.getParent() != null) {
                    Files.createDirectories(ignorePath.getParent());
                }
                String existing = Files.exists(ignorePath) ? Files.readString(ignorePath) : "";
                if (containsIgnoreRule(existing, ignoreRule)) {
                    return;
                }
                String separator = existing.endsWith("\n") || existing.isEmpty() ? "" : "\n";
                String prefix = existing.isEmpty() ? "" : "\n";
                String addition = separator
                    + prefix
                    + "# Added by LingCe AI File Cleaner: " + reason
                    + "\n" + ignoreRule
                    + "\n";
                Files.writeString(ignorePath, existing + addition, StandardCharsets.UTF_8);
                LocalFileSystem.getInstance().refreshAndFindFileByNioFile(ignorePath);
            } catch (IOException e) {
                LOG.warn("Failed to update ignore file: " + ignorePath, e);
            }
        });
    }

    private boolean containsIgnoreRule(String existing, String rule) {
        return existing.lines().map(String::trim).anyMatch(line -> line.equals(rule));
    }

    private void notifySuspicious(VirtualFile file, FileClassification classification) {
        if (!file.isValid() || !isInsideProject(file)) {
            return;
        }

        ApplicationManager.getApplication().invokeLater(() -> {
            if (project.isDisposed() || !file.isValid()) {
                return;
            }

            Notification notification = NotificationGroupManager.getInstance()
                .getNotificationGroup(NOTIFICATION_GROUP)
                .createNotification(
                    "Suspicious file detected",
                    FileUtil.toSystemDependentName(relativePath(file)) + " - " + classification.reason(),
                    NotificationType.WARNING
                );
            notification.addAction(new NotificationAction("Move to quarantine") {
                @Override
                public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
                    moveToQuarantine(file);
                    notification.expire();
                }
            });
            notification.addAction(new NotificationAction("Delete") {
                @Override
                public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
                    deleteFile(file, "Deleted by user from suspicious file notification");
                    notification.expire();
                }
            });
            notification.notify(project);
        });
    }

    private void moveToQuarantine(VirtualFile file) {
        Path basePath = getBasePath();
        if (basePath == null || !file.isValid()) {
            return;
        }

        AiCleanerSettings.StateData settings = AiCleanerSettings.getInstance().getState();
        String directory = AiCleanerSettings.isBlank(settings.quarantineDirectory)
            ? ".ai-cleaner/quarantine"
            : settings.quarantineDirectory.trim();
        Path configured = Path.of(directory);
        Path targetPath = configured.isAbsolute()
            ? configured
            : basePath.resolve(configured).normalize();
        Path stampedTargetPath = targetPath.resolve(LocalDateTime.now().format(QUARANTINE_FORMAT));

        ApplicationManager.getApplication().invokeLater(() ->
            WriteCommandAction.runWriteCommandAction(project, () -> {
                try {
                    if (!file.isValid()) {
                        return;
                    }
                    VirtualFile targetDirectory = VfsUtil.createDirectories(stampedTargetPath.toString());
                    file.move(this, targetDirectory);
                    notifyInfo("Moved suspicious file to " + FileUtil.toSystemDependentName(stampedTargetPath.toString()));
                } catch (IOException e) {
                    LOG.warn("Failed to move suspicious file to quarantine: " + file.getPath(), e);
                    notifyError("Failed to move suspicious file: " + e.getMessage());
                }
            })
        );
    }

    private void deleteFile(VirtualFile file, String reason) {
        ApplicationManager.getApplication().invokeLater(() ->
            WriteCommandAction.runWriteCommandAction(project, () -> {
                try {
                    if (file.isValid()) {
                        file.delete(this);
                        LOG.info(reason);
                    }
                } catch (IOException e) {
                    LOG.warn("Failed to delete file: " + file.getPath(), e);
                    notifyError("Failed to delete " + file.getName() + ": " + e.getMessage());
                }
            })
        );
    }

    private void notifyInfo(String message) {
        NotificationGroupManager.getInstance()
            .getNotificationGroup(NOTIFICATION_GROUP)
            .createNotification("LingCe AI Cleaner", message, NotificationType.INFORMATION)
            .notify(project);
    }

    private void notifyError(String message) {
        NotificationGroupManager.getInstance()
            .getNotificationGroup(NOTIFICATION_GROUP)
            .createNotification("LingCe AI Cleaner", message, NotificationType.ERROR)
            .notify(project);
    }

    private boolean isInsideProject(VirtualFile file) {
        VirtualFile baseDir = getBaseDir();
        return baseDir != null && VfsUtilCore.isAncestor(baseDir, file, false);
    }

    private String relativePath(VirtualFile file) {
        VirtualFile baseDir = getBaseDir();
        if (baseDir == null) {
            return file.getName();
        }
        String relative = VfsUtilCore.getRelativePath(file, baseDir, '/');
        return relative == null ? file.getName() : relative;
    }

    private @Nullable VirtualFile getBaseDir() {
        Path basePath = getBasePath();
        if (basePath == null) {
            return null;
        }
        return LocalFileSystem.getInstance().findFileByNioFile(basePath);
    }

    private @Nullable Path getBasePath() {
        String basePath = project.getBasePath();
        if (AiCleanerSettings.isBlank(basePath)) {
            return null;
        }
        return Path.of(basePath);
    }
}
