# Generated by Django 5.2.17 on 2026-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_id', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('slice_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'slices',
            },
        ),
        migrations.CreateModel(
            name='GateAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_name', models.CharField(max_length=64)),
                ('slice_id', models.CharField(max_length=64)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'gate_attempts',
                'constraints': [models.UniqueConstraint(fields=('gate_name', 'slice_id'), name='uniq_gate_slice')],
            },
        ),
    ]
