package com.lingce.cleankeeper.service

import com.intellij.openapi.vfs.VirtualFile
import com.lingce.cleankeeper.model.ClassificationSource
import com.lingce.cleankeeper.model.FileCategory
import com.lingce.cleankeeper.model.FileClassification
import com.lingce.cleankeeper.settings.CleanKeeperSettings
import java.nio.charset.StandardCharsets

object HeuristicClassifier {

    private val DEFAULT_TMP_PATTERNS = listOf(
        Regex("""\.tmp$""", RegexOption.IGNORE_CASE),
        Regex("""\.temp$""", RegexOption.IGNORE_CASE),
        Regex("""\.swp$""", RegexOption.IGNORE_CASE),
        Regex("""\.swo$""", RegexOption.IGNORE_CASE),
        Regex("""~$"""),
        Regex("""\.bak$""", RegexOption.IGNORE_CASE),
        Regex("""\.old$""", RegexOption.IGNORE_CASE),
        Regex("""\.orig$""", RegexOption.IGNORE_CASE),
        Regex("""^\.DS_Store$"""),
        Regex("""^Thumbs\.db$""", RegexOption.IGNORE_CASE),
        Regex("""^desktop\.ini$""", RegexOption.IGNORE_CASE),
        Regex("""\.log$""", RegexOption.IGNORE_CASE),
        Regex("""^~\$.*"""),
        Regex("""\.part$""", RegexOption.IGNORE_CASE),
        Regex("""\.crdownload$""", RegexOption.IGNORE_CASE),
    )

    private val DEFAULT_AI_CONFIG_PATTERNS = listOf(
        Regex("""^\.cursorrules$""", RegexOption.IGNORE_CASE),
        Regex("""^\.cursorignore$""", RegexOption.IGNORE_CASE),
        Regex("""^AGENTS\.md$""", RegexOption.IGNORE_CASE),
        Regex("""^CLAUDE\.md$""", RegexOption.IGNORE_CASE),
        Regex("""^\.aider.*""", RegexOption.IGNORE_CASE),
        Regex("""^\.copilot.*""", RegexOption.IGNORE_CASE),
        Regex("""^\.cline.*""", RegexOption.IGNORE_CASE),
        Regex("""^\.continue.*""", RegexOption.IGNORE_CASE),
        Regex("""^\.windsurfrules$""", RegexOption.IGNORE_CASE),
        Regex("""^\.ai/.*""", RegexOption.IGNORE_CASE),
        Regex("""^\.cursor/.*""", RegexOption.IGNORE_CASE),
        Regex("""^ai-file-cleankeeper\.xml$""", RegexOption.IGNORE_CASE),
    )

    private val DEFAULT_PROJECT_CONFIG_PATTERNS = listOf(
        Regex("""^\.env(\..+)?$""", RegexOption.IGNORE_CASE),
        Regex("""^\.env\.local$""", RegexOption.IGNORE_CASE),
        Regex("""^\.env\.example$""", RegexOption.IGNORE_CASE),
        Regex("""^local\.properties$""", RegexOption.IGNORE_CASE),
        Regex("""^\.idea/workspace\.xml$""", RegexOption.IGNORE_CASE),
        Regex("""^\.idea/shelf/.*""", RegexOption.IGNORE_CASE),
        Regex("""^\.vscode/settings\.json$""", RegexOption.IGNORE_CASE),
        Regex("""^\.vscode/launch\.json$""", RegexOption.IGNORE_CASE),
        Regex("""^\.npmrc$""", RegexOption.IGNORE_CASE),
        Regex("""^\.pypirc$""", RegexOption.IGNORE_CASE),
        Regex("""^secrets\.(ya?ml|json|properties)$""", RegexOption.IGNORE_CASE),
    )

    private val AI_GENERATED_NAME_PATTERNS = listOf(
        Regex("""^(draft|temp|scratch|test_output|ai_output|generated)[-_].*""", RegexOption.IGNORE_CASE),
        Regex(""".*_(draft|generated|ai|tmp)\.(md|txt|json|ts|js|py)$""", RegexOption.IGNORE_CASE),
        Regex("""^Untitled.*""", RegexOption.IGNORE_CASE),
        Regex("""^output\.(md|txt|json)$""", RegexOption.IGNORE_CASE),
    )

    private val AI_CONTENT_MARKERS = listOf(
        "generated by ai",
        "generated by chatgpt",
        "generated by claude",
        "generated by copilot",
        "auto-generated by",
        "this file was generated",
        "do not edit manually",
        "ai-generated",
        "as an ai language model",
    )

  fun classify(file: VirtualFile, projectRelativePath: String, content: String?): FileClassification? {
        val settings = CleanKeeperSettings.getInstance()
        val name = file.name
        val path = projectRelativePath.replace('\\', '/')

        val tmpPatterns = DEFAULT_TMP_PATTERNS + settings.customTmpPatterns.map { Regex(it) }
        for (pattern in tmpPatterns) {
            if (pattern.containsMatchIn(name) || pattern.containsMatchIn(path)) {
                return FileClassification(FileCategory.TMP_FILE, 0.95, "匹配临时文件规则: $pattern", ClassificationSource.HEURISTIC)
            }
        }

        val aiConfigPatterns = DEFAULT_AI_CONFIG_PATTERNS + settings.customAiConfigPatterns.map { Regex(it) }
        for (pattern in aiConfigPatterns) {
            if (pattern.containsMatchIn(name) || pattern.containsMatchIn(path)) {
                return FileClassification(FileCategory.AI_CONFIG, 0.92, "匹配 AI 配置规则: $pattern", ClassificationSource.HEURISTIC)
            }
        }

        val projectConfigPatterns = DEFAULT_PROJECT_CONFIG_PATTERNS + settings.customIgnorePatterns.map { Regex(it) }
        for (pattern in projectConfigPatterns) {
            if (pattern.containsMatchIn(name) || pattern.containsMatchIn(path)) {
                return FileClassification(FileCategory.PROJECT_CONFIG, 0.9, "匹配项目配置规则: $pattern", ClassificationSource.HEURISTIC)
            }
        }

        for (pattern in AI_GENERATED_NAME_PATTERNS) {
            if (pattern.containsMatchIn(name)) {
                return FileClassification(FileCategory.AI_GENERATED_USELESS, 0.75, "文件名疑似 AI 产物: $name", ClassificationSource.HEURISTIC)
            }
        }

        if (!content.isNullOrBlank() && file.length < 512_000) {
            val lower = content.lowercase()
            for (marker in AI_CONTENT_MARKERS) {
                if (lower.contains(marker)) {
                    return FileClassification(FileCategory.AI_GENERATED_USELESS, 0.8, "内容包含 AI 生成标记: $marker", ClassificationSource.HEURISTIC)
                }
            }

            if (isLikelyAiScaffold(content, name)) {
                return FileClassification(FileCategory.AI_GENERATED_USELESS, 0.7, "内容为典型 AI 脚手架/示例代码", ClassificationSource.HEURISTIC)
            }
        }

        if (isSuspiciousLocation(path, name)) {
            return FileClassification(FileCategory.SUSPICIOUS, 0.55, "文件位于非常规路径: $path", ClassificationSource.HEURISTIC)
        }

        return null
    }

    fun readContent(file: VirtualFile, maxBytes: Int = 32_768): String? {
        if (file.isDirectory || file.length <= 0) return null
        return try {
            val bytes = file.contentsToByteArray()
            val slice = bytes.copyOf(minOf(bytes.size, maxBytes))
            String(slice, StandardCharsets.UTF_8)
        } catch (_: Exception) {
            null
        }
    }

    private fun isLikelyAiScaffold(content: String, name: String): Boolean {
        val lines = content.lines()
        if (lines.size < 3) return false

        val hasTodoPlaceholder = content.contains("TODO:") && content.contains("implement")
        val hasLorem = content.contains("lorem ipsum", ignoreCase = true)
        val hasExampleOnly = name.contains("example", ignoreCase = true) &&
            (content.contains("example usage", ignoreCase = true) || content.contains("示例", ignoreCase = false))

        val boilerplateRatio = lines.count { line ->
            val t = line.trim()
            t.isEmpty() || t.startsWith("//") || t.startsWith("#") || t.startsWith("/*") || t.startsWith("*")
        }.toDouble() / lines.size

        return hasTodoPlaceholder || hasLorem || (hasExampleOnly && boilerplateRatio > 0.6)
    }

    private fun isSuspiciousLocation(path: String, name: String): Boolean {
        if (path.contains("/node_modules/") || path.contains("/.git/")) return false
        val suspiciousDirs = listOf("/", "root", "unknown", "misc", "random")
        val top = path.substringBefore('/')
        if (top in suspiciousDirs && !name.contains('.')) return true
        if (name.startsWith(".") && name.length > 20 && !name.contains('.')) return true
        return false
    }
}
