package com.lingce.aijanitor.classify

import com.intellij.openapi.vfs.VirtualFile
import java.util.Locale

/**
 * Fast, offline, rule-based classifier. Always runs first; the AI classifier
 * only needs to weigh in on the leftovers it can't decide on.
 */
object HeuristicClassifier {

    // Temp / junk file name patterns (exact names or suffixes).
    private val TEMP_EXACT = setOf(
        ".ds_store", "thumbs.db", "desktop.ini", "npm-debug.log", "yarn-error.log",
    )
    private val TEMP_SUFFIXES = listOf(
        ".tmp", ".temp", ".bak", ".old", ".swp", ".swo", ".orig", ".rej",
        ".log", ".pyc", ".pyo", ".class", ".o", ".obj", ".lock~", "~",
        ".cache", ".stackdump",
    )
    private val TEMP_DIR_NAMES = setOf(
        "__pycache__", ".cache", ".tmp", "tmp", "temp",
    )

    // AI tool config files / directories.
    private val AI_CONFIG_EXACT = setOf(
        ".cursorrules", ".cursorignore", ".windsurfrules", ".aider.conf.yml",
        ".aiderignore", "claude.md", "agents.md", "agent.md", ".clinerules",
        "copilot-instructions.md", ".continuerc.json", "gemini.md",
        ".roomodes", ".aiexclude",
    )
    private val AI_CONFIG_DIRS = setOf(
        ".cursor", ".continue", ".aider", ".codeium", ".tabnine", ".github/copilot",
        ".claude", ".windsurf", ".roo", ".cline",
    )
    private val AI_CONFIG_PREFIXES = listOf(".aider")

    // Local / IDE / project config that typically should not be committed.
    private val PROJECT_CONFIG_EXACT = setOf(
        ".editorconfig", ".env.local", ".env.development.local", ".env.production.local",
    )
    private val PROJECT_CONFIG_SUFFIXES = listOf(".iml")
    private val PROJECT_CONFIG_DIRS = setOf(".idea", ".vscode", ".fleet", ".settings")

    // Strong textual markers of raw, un-edited AI assistant output.
    private val AI_TEXT_MARKERS = listOf(
        "as an ai language model",
        "i'm an ai language model",
        "i cannot fulfill this request",
        "here's the complete implementation",
        "here is the complete implementation",
        "here's an example implementation",
        "certainly! here",
        "sure! here's",
        "sure, here's",
        "i've generated",
        "i have generated",
        "generated by chatgpt",
        "generated by gpt",
        "generated by claude",
        "this code was generated by ai",
        "this file was generated by ai",
        "<<<<<<< ",
        ">>>>>>> ",
    )

    private val PLACEHOLDER_MARKERS = listOf(
        "lorem ipsum",
        "your code here",
        "// todo: implement",
        "# todo: implement",
        "todo: add your",
        "replace this with your",
        "example placeholder",
        "this is a sample",
        "this is a placeholder",
    )

    fun classify(file: VirtualFile, extraTempGlobs: List<String>): ClassificationResult {
        val name = file.name
        val lower = name.lowercase(Locale.ROOT)
        val path = file.path.replace('\\', '/')
        val lowerPath = path.lowercase(Locale.ROOT)

        // Directories: classify config dirs; everything else is left to per-file scan.
        if (file.isDirectory) {
            aiConfigDirMatch(lowerPath)?.let {
                return result(file, FileCategory.AI_CONFIG, 0.95, "AI 工具配置目录: $it")
            }
            PROJECT_CONFIG_DIRS.firstOrNull { lowerPath.endsWith("/$it") || lower == it }?.let {
                return result(file, FileCategory.PROJECT_CONFIG, 0.9, "IDE/项目配置目录: $it")
            }
            TEMP_DIR_NAMES.firstOrNull { lower == it }?.let {
                return result(file, FileCategory.TEMP, 0.85, "临时目录: $it")
            }
            return result(file, FileCategory.KEEP, 0.5, "普通目录")
        }

        // 1. User-defined temp globs win first.
        extraTempGlobs.firstOrNull { globMatch(it, name) || globMatch(it, path) }?.let {
            return result(file, FileCategory.TEMP, 0.9, "命中自定义临时规则: $it")
        }

        // 2. Temp / junk.
        if (lower in TEMP_EXACT) {
            return result(file, FileCategory.TEMP, 0.97, "已知临时/系统文件: $name")
        }
        TEMP_SUFFIXES.firstOrNull { lower.endsWith(it) }?.let {
            return result(file, FileCategory.TEMP, 0.9, "临时文件后缀: $it")
        }
        if (lowerPath.split('/').any { it in TEMP_DIR_NAMES }) {
            return result(file, FileCategory.TEMP, 0.8, "位于临时目录中")
        }

        // 3. AI tool config.
        if (lower in AI_CONFIG_EXACT) {
            return result(file, FileCategory.AI_CONFIG, 0.95, "AI 工具配置文件: $name")
        }
        if (AI_CONFIG_PREFIXES.any { lower.startsWith(it) }) {
            return result(file, FileCategory.AI_CONFIG, 0.85, "AI 工具配置文件: $name")
        }
        aiConfigDirMatch(lowerPath)?.let {
            return result(file, FileCategory.AI_CONFIG, 0.9, "位于 AI 配置目录: $it")
        }

        // 4. Project / IDE config.
        if (lower in PROJECT_CONFIG_EXACT) {
            return result(file, FileCategory.PROJECT_CONFIG, 0.85, "项目/本地配置: $name")
        }
        PROJECT_CONFIG_SUFFIXES.firstOrNull { lower.endsWith(it) }?.let {
            return result(file, FileCategory.PROJECT_CONFIG, 0.85, "IDE 模块文件: $it")
        }
        PROJECT_CONFIG_DIRS.firstOrNull { lowerPath.contains("/$it/") }?.let {
            return result(file, FileCategory.PROJECT_CONFIG, 0.85, "位于 IDE 配置目录: $it")
        }

        // 5. Content-based AI-generated detection for small text files.
        val content = readSnippet(file)
        if (content != null) {
            val lc = content.lowercase(Locale.ROOT)
            AI_TEXT_MARKERS.firstOrNull { lc.contains(it) }?.let {
                return result(file, FileCategory.AI_GENERATED_USELESS, 0.85, "包含 AI 输出特征: \"$it\"")
            }
            val placeholders = PLACEHOLDER_MARKERS.count { lc.contains(it) }
            if (placeholders >= 2) {
                return result(
                    file, FileCategory.AI_GENERATED_USELESS, 0.7,
                    "包含多处占位/模板内容 ($placeholders 处)",
                )
            }
            if (file.length == 0L) {
                return result(file, FileCategory.SUSPICIOUS, 0.5, "空文件")
            }
        }

        // Default: keep, low confidence so the AI classifier can refine it.
        return result(file, FileCategory.KEEP, 0.4, "未命中规则")
    }

    private fun aiConfigDirMatch(lowerPath: String): String? =
        AI_CONFIG_DIRS.firstOrNull { lowerPath.contains("/$it/") || lowerPath.endsWith("/$it") }

    private fun readSnippet(file: VirtualFile): String? {
        // Only inspect reasonably-sized text-like files.
        if (file.length > 256 * 1024) return null
        val ext = file.extension?.lowercase(Locale.ROOT)
        if (ext != null && ext in BINARY_EXTENSIONS) return null
        return try {
            val bytes = file.contentsToByteArray()
            if (looksBinary(bytes)) null else String(bytes, Charsets.UTF_8)
        } catch (_: Exception) {
            null
        }
    }

    private fun looksBinary(bytes: ByteArray): Boolean {
        val sample = bytes.take(2048)
        if (sample.isEmpty()) return false
        val nonText = sample.count { b ->
            val i = b.toInt() and 0xFF
            i == 0 || (i < 0x09)
        }
        return nonText > 0
    }

    private val BINARY_EXTENSIONS = setOf(
        "png", "jpg", "jpeg", "gif", "ico", "webp", "bmp", "pdf", "zip", "jar",
        "gz", "tar", "7z", "rar", "exe", "dll", "so", "dylib", "bin", "class",
        "woff", "woff2", "ttf", "eot", "mp3", "mp4", "mov", "avi", "wav",
    )

    /** Very small glob matcher supporting `*` and `?`. */
    private fun globMatch(glob: String, value: String): Boolean {
        if (glob.isBlank()) return false
        val regex = buildString {
            append('^')
            for (c in glob.trim()) {
                when (c) {
                    '*' -> append(".*")
                    '?' -> append('.')
                    '.', '(', ')', '+', '|', '^', '$', '@', '%', '{', '}', '[', ']', '\\' ->
                        append('\\').append(c)
                    else -> append(c)
                }
            }
            append('$')
        }
        return Regex(regex, RegexOption.IGNORE_CASE).matches(value)
    }

    private fun result(
        file: VirtualFile,
        category: FileCategory,
        confidence: Double,
        reason: String,
    ) = ClassificationResult(file, category, category.defaultAction(), confidence, reason, "heuristic")
}
