package com.lingce.cleaner.util

import java.nio.file.Path
import kotlin.io.path.extension
import kotlin.io.path.fileName
import kotlin.io.path.name

object FilePatterns {
    private val tmpExtensions = setOf("tmp", "temp", "bak", "swp", "swo", "old")
    private val tmpNameMarkers = listOf("~", ".tmp", ".temp", "copy(", "副本")

    private val aiNameMarkers = listOf(
        "chatgpt",
        "gpt",
        "claude",
        "copilot",
        "gemini",
        "ai_generated",
        "generated_by_ai",
        "llm_output",
        "autogen"
    )

    private val aiContentMarkers = listOf(
        "generated by ai",
        "generated by chatgpt",
        "generated by claude",
        "as an ai",
        "here's the code",
        "i cannot run code",
        "placeholder implementation"
    )

    private val suspiciousExtensions = setOf("exe", "dll", "bat", "cmd", "ps1", "sh")
    private val suspiciousNameRegex = Regex("^[a-z0-9]{20,}\\.[a-z0-9]{1,6}$")

    private val projectConfigMarkers = listOf(
        ".idea/",
        ".vscode/",
        ".classpath",
        ".project",
        ".settings/",
        ".iml",
        ".ipr",
        ".iws"
    )

    private val aiConfigMarkers = listOf(
        ".cursor/",
        ".aider",
        ".copilot",
        ".continue",
        "prompt-config",
        "llm-config",
        "ai-config"
    )

    fun isTmpFile(path: Path): Boolean {
        val name = path.fileName?.name?.lowercase() ?: return false
        val ext = path.extension.lowercase()
        return ext in tmpExtensions || tmpNameMarkers.any { marker -> name.contains(marker) }
    }

    fun isProjectConfigFile(relativePath: String): Boolean {
        val normalized = relativePath.lowercase()
        return projectConfigMarkers.any { marker ->
            if (marker.startsWith(".")) normalized.contains(marker) else normalized.endsWith(marker)
        }
    }

    fun isAiConfigFile(relativePath: String): Boolean {
        val normalized = relativePath.lowercase()
        return aiConfigMarkers.any { marker -> normalized.contains(marker) }
    }

    fun looksAiGenerated(path: Path, content: String): Boolean {
        val name = path.fileName?.name?.lowercase() ?: ""
        val normalized = content.lowercase()
        val nameHits = aiNameMarkers.count { marker -> name.contains(marker) }
        val contentHits = aiContentMarkers.count { marker -> normalized.contains(marker) }
        return nameHits >= 1 || contentHits >= 2
    }

    fun looksSuspicious(path: Path, fileSizeBytes: Long): Boolean {
        val name = path.fileName?.name?.lowercase() ?: return false
        val ext = path.extension.lowercase()
        if (ext in suspiciousExtensions) return true
        if (suspiciousNameRegex.matches(name)) return true
        return fileSizeBytes > 20 * 1024 * 1024
    }
}
