package com.lingce.aifilecleaner.service

import com.lingce.aifilecleaner.model.FileCategory
import com.lingce.aifilecleaner.settings.CleanerSettingsState
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.nio.file.Path
import java.time.Duration
import java.util.Locale

class AiFileClassifier {
    private val tmpNameRegex = Regex(".*(\\.tmp|\\.temp|\\.swp|\\.swo|\\.bak|\\.orig|~)$", RegexOption.IGNORE_CASE)
    private val aiConfigNameRegex = Regex(
        "^(\\.cursorrules|\\.cursorignore|\\.aider\\..*|\\.copilot.*|\\.codeium.*|\\.windsurfrules|\\.clinerules|\\.roo.*)$",
        RegexOption.IGNORE_CASE
    )
    private val rootConfigRegex = Regex("^(\\.env(\\..*)?|\\.vscode/.+|\\.idea/.+|.+\\.iml)$", RegexOption.IGNORE_CASE)
    private val suspiciousNameRegex = Regex(".*(backup|unknown|random|generated|draft|copy).*", RegexOption.IGNORE_CASE)
    private val randomTokenRegex = Regex("[a-f0-9]{24,}", RegexOption.IGNORE_CASE)

    private val httpClient: HttpClient = HttpClient.newBuilder()
        .connectTimeout(Duration.ofSeconds(5))
        .build()

    fun classify(
        path: Path,
        relativePath: String,
        text: String?,
        settings: CleanerSettingsState.State
    ): FileCategory {
        val fileName = path.fileName.toString()
        if (isTmpFile(fileName)) {
            return FileCategory.TMP
        }
        if (isConfigOrAiConfig(relativePath, fileName)) {
            return FileCategory.CONFIG_OR_AI_CONFIG
        }

        if (text != null && isLikelyAiJunkByHeuristics(text)) {
            return FileCategory.AI_JUNK
        }

        val remoteCategory = text?.let { classifyByRemoteModel(relativePath, it, settings) }
        if (remoteCategory != null && remoteCategory != FileCategory.SAFE) {
            return remoteCategory
        }

        if (isSuspicious(relativePath, fileName, text)) {
            return FileCategory.SUSPICIOUS
        }
        return FileCategory.SAFE
    }

    private fun isTmpFile(fileName: String): Boolean {
        val lower = fileName.lowercase(Locale.getDefault())
        return tmpNameRegex.matches(lower) ||
            lower == ".ds_store" ||
            lower == "thumbs.db"
    }

    private fun isConfigOrAiConfig(relativePath: String, fileName: String): Boolean {
        val normalized = relativePath.replace('\\', '/')
        return aiConfigNameRegex.matches(fileName) || rootConfigRegex.matches(normalized)
    }

    private fun isLikelyAiJunkByHeuristics(text: String): Boolean {
        val lower = text.lowercase(Locale.getDefault())
        val aiMarkers = listOf(
            "generated by chatgpt",
            "ai-generated",
            "this file is generated by ai",
            "由 ai 生成",
            "as an ai",
            "placeholder implementation",
            "todo: replace with real logic"
        )
        val noisyMarkers = listOf(
            "lorem ipsum",
            "dummy data",
            "sample output only",
            "示例占位",
            "临时占位"
        )
        val hasAiMarker = aiMarkers.any { lower.contains(it) }
        val hasNoisyMarker = noisyMarkers.any { lower.contains(it) }
        return hasAiMarker && hasNoisyMarker
    }

    private fun isSuspicious(relativePath: String, fileName: String, text: String?): Boolean {
        val normalized = relativePath.replace('\\', '/')
        if (normalized.startsWith(".project-cleaner/")) {
            return false
        }
        if (fileName.startsWith(".") &&
            !fileName.startsWith(".git") &&
            !fileName.startsWith(".env") &&
            !fileName.startsWith(".editorconfig")
        ) {
            return true
        }
        if (suspiciousNameRegex.matches(fileName) || randomTokenRegex.containsMatchIn(fileName)) {
            return true
        }
        if (text != null) {
            val lower = text.lowercase(Locale.getDefault())
            if (lower.contains("rm -rf /") || lower.contains("invoke-webrequest")) {
                return true
            }
        }
        return false
    }

    private fun classifyByRemoteModel(
        relativePath: String,
        text: String,
        settings: CleanerSettingsState.State
    ): FileCategory? {
        val apiKey = settings.apiKey.trim()
        val baseUrl = settings.baseUrl.trim().trimEnd('/')
        if (apiKey.isEmpty() || baseUrl.isEmpty()) {
            return null
        }

        val endpoint = "$baseUrl/v1/chat/completions"
        val snippet = text.take(3000)
        val prompt = """
            你是文件审计器。请严格返回一个标签，不要解释：
            SAFE / AI_JUNK / SUSPICIOUS
            文件路径: $relativePath
            文件内容:
            $snippet
        """.trimIndent()
        val payload = """
            {
              "model": "gpt-4o-mini",
              "temperature": 0,
              "messages": [
                {"role":"system","content":"You are a strict classifier. Output one label only: SAFE, AI_JUNK, or SUSPICIOUS."},
                {"role":"user","content":"${escapeJson(prompt)}"}
              ]
            }
        """.trimIndent()

        return try {
            val request = HttpRequest.newBuilder()
                .uri(URI.create(endpoint))
                .timeout(Duration.ofSeconds(12))
                .header("Authorization", "Bearer $apiKey")
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(payload))
                .build()
            val response = httpClient.send(request, HttpResponse.BodyHandlers.ofString())
            if (response.statusCode() !in 200..299) {
                null
            } else {
                val bodyUpper = response.body().uppercase(Locale.getDefault())
                when {
                    bodyUpper.contains("AI_JUNK") -> FileCategory.AI_JUNK
                    bodyUpper.contains("SUSPICIOUS") -> FileCategory.SUSPICIOUS
                    bodyUpper.contains("SAFE") -> FileCategory.SAFE
                    else -> null
                }
            }
        } catch (_: Exception) {
            null
        }
    }

    private fun escapeJson(raw: String): String {
        return buildString(raw.length + 16) {
            raw.forEach { ch ->
                when (ch) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(ch)
                }
            }
        }
    }
}
