package com.lingce.aifilecleaner.classifier;

import java.util.List;
import java.util.regex.Pattern;

public final class HeuristicFileClassifier implements FileClassifier {
    private static final List<String> TEMPORARY_SUFFIXES = List.of(
            ".tmp", ".temp", ".bak", ".backup", ".old", ".orig", ".rej", ".swp", ".swo", ".pid"
    );
    private static final List<String> TEMPORARY_PATH_PARTS = List.of(
            "/tmp/", "/temp/", "/.tmp/", "/.cache/", "/cache/", "/scratch/", "/ai-output/", "/ai-temp/"
    );
    private static final List<String> PROJECT_CONFIG_PATHS = List.of(
            ".idea/", ".vscode/", ".settings/", ".project", ".classpath", ".factorypath", ".metadata/"
    );
    private static final List<String> AI_CONFIG_PATHS = List.of(
            ".cursor/", ".cursorignore", ".cursorrules", ".windsurf/", ".windsurfrules",
            ".continue/", ".aider", ".aider.conf.yml", ".aider.conf.yaml", ".claude/",
            "claude.md", "agents.md", ".github/copilot-instructions.md"
    );
    private static final List<String> AI_MARKERS = List.of(
            "generated by chatgpt",
            "generated with chatgpt",
            "generated by claude",
            "generated with claude",
            "generated by cursor",
            "ai-generated",
            "this file was generated by an ai",
            "created by an ai assistant"
    );
    private static final Pattern AI_SCRATCH_NAME = Pattern.compile(
            "(^|[-_.])(ai|llm|chatgpt|claude|cursor|copilot|windsurf)([-_.].*)?(scratch|draft|output|generated|tmp|temp)([-_.]|$)"
    );

    @Override
    public FileClassification classify(FileSample sample) {
        String path = sample.normalizedRelativePath();
        String name = sample.fileName().toLowerCase();

        if (isTemporary(path, name)) {
            return new FileClassification(
                    FileClassification.Kind.TEMPORARY,
                    FileClassification.RecommendedAction.DELETE,
                    0.97,
                    "Name or path matches temporary-file patterns.",
                    "heuristic"
            );
        }

        if (matchesAnyConfig(path, PROJECT_CONFIG_PATHS)) {
            return new FileClassification(
                    FileClassification.Kind.PROJECT_CONFIG,
                    FileClassification.RecommendedAction.IGNORE_EXCLUDE,
                    0.92,
                    "Path matches IDE/project configuration patterns.",
                    "heuristic"
            );
        }

        if (matchesAnyConfig(path, AI_CONFIG_PATHS)) {
            return new FileClassification(
                    FileClassification.Kind.AI_CONFIG,
                    FileClassification.RecommendedAction.IGNORE_EXCLUDE,
                    0.94,
                    "Path matches AI assistant configuration patterns.",
                    "heuristic"
            );
        }

        if (!sample.binary() && containsAiMarker(sample.contentSnippet())) {
            return new FileClassification(
                    FileClassification.Kind.AI_GENERATED,
                    FileClassification.RecommendedAction.ASK,
                    0.86,
                    "Content contains an AI-generated marker; user confirmation is required before cleanup.",
                    "heuristic"
            );
        }

        if (AI_SCRATCH_NAME.matcher(name).find() || path.contains("/ai-generated/") || path.contains("/generated-by-ai/")) {
            return new FileClassification(
                    FileClassification.Kind.AI_GENERATED,
                    FileClassification.RecommendedAction.DELETE,
                    0.84,
                    "File name/path indicates AI scratch, generated output, or temporary AI artifact.",
                    "heuristic"
            );
        }

        if (looksLikeChatTranscript(sample)) {
            return new FileClassification(
                    FileClassification.Kind.SUSPICIOUS,
                    FileClassification.RecommendedAction.ASK,
                    0.74,
                    "File resembles an AI chat transcript or prompt dump.",
                    "heuristic"
            );
        }

        return FileClassification.safe("No cleanup patterns matched.");
    }

    private static boolean isTemporary(String path, String name) {
        if (name.endsWith("~")) {
            return true;
        }
        for (String suffix : TEMPORARY_SUFFIXES) {
            if (name.endsWith(suffix)) {
                return true;
            }
        }
        for (String part : TEMPORARY_PATH_PARTS) {
            if (path.contains(part)) {
                return true;
            }
        }
        return false;
    }

    private static boolean matchesAnyConfig(String path, List<String> patterns) {
        for (String pattern : patterns) {
            if (pattern.endsWith("/") && (path.equals(pattern.substring(0, pattern.length() - 1)) || path.startsWith(pattern))) {
                return true;
            }
            if (!pattern.endsWith("/") && (path.equals(pattern) || path.endsWith("/" + pattern) || path.startsWith(pattern + "/"))) {
                return true;
            }
        }
        return false;
    }

    private static boolean containsAiMarker(String snippet) {
        String text = snippet.toLowerCase();
        for (String marker : AI_MARKERS) {
            if (text.contains(marker)) {
                return true;
            }
        }
        return false;
    }

    private static boolean looksLikeChatTranscript(FileSample sample) {
        String name = sample.fileName().toLowerCase();
        if (!(name.endsWith(".md") || name.endsWith(".txt") || name.endsWith(".json"))) {
            return false;
        }
        String text = sample.contentSnippet().toLowerCase();
        return text.contains("user:")
                && (text.contains("assistant:") || text.contains("\"role\":\"assistant\"") || text.contains("\"role\": \"assistant\""))
                && (text.contains("prompt") || text.contains("completion") || text.contains("chat"));
    }
}
