import type { ApiInterface } from "../types.js";

/**
 * Built-in demo interfaces so the cockpit is fully explorable without any
 * external YAPI instance. They mimic a typical e-commerce backend.
 */
export const demoInterfaces: ApiInterface[] = [
  {
    id: "1001",
    title: "用户登录",
    method: "POST",
    path: "/api/auth/login",
    catName: "认证",
    reqParams: [],
    reqQuery: [],
    reqHeaders: [],
    reqBodyType: "json",
    reqBody: { username: "string", password: "string", captcha: "string" },
    resBody: { code: 0, data: { token: "string", expiresIn: 7200 }, message: "ok" },
    updatedAt: Date.now(),
  },
  {
    id: "1002",
    title: "获取用户资料",
    method: "GET",
    path: "/api/users/{userId}",
    catName: "用户",
    reqParams: [{ name: "userId", type: "string", required: true, desc: "用户 ID" }],
    reqQuery: [{ name: "fields", type: "string", required: false, desc: "返回字段过滤,逗号分隔" }],
    reqHeaders: [{ name: "Authorization", type: "string", required: true, desc: "Bearer Token" }],
    reqBodyType: "none",
    resBody: { code: 0, data: { id: "string", name: "string", email: "string", level: 1 } },
    updatedAt: Date.now(),
  },
  {
    id: "1003",
    title: "创建订单",
    method: "POST",
    path: "/api/orders",
    catName: "订单",
    reqParams: [],
    reqQuery: [],
    reqHeaders: [{ name: "Authorization", type: "string", required: true, desc: "Bearer Token" }],
    reqBodyType: "json",
    reqBody: {
      userId: "string",
      items: [{ skuId: "string", quantity: 1, price: 0 }],
      couponCode: "string",
      remark: "string",
    },
    resBody: { code: 0, data: { orderId: "string", payAmount: 0, status: "created" } },
    updatedAt: Date.now(),
  },
  {
    id: "1004",
    title: "分页查询商品",
    method: "GET",
    path: "/api/products",
    catName: "商品",
    reqParams: [],
    reqQuery: [
      { name: "keyword", type: "string", required: false, desc: "搜索关键字" },
      { name: "category", type: "string", required: false, desc: "分类" },
      { name: "page", type: "integer", required: false, desc: "页码", example: "1" },
      { name: "pageSize", type: "integer", required: false, desc: "每页数量", example: "20" },
    ],
    reqHeaders: [],
    reqBodyType: "none",
    resBody: { code: 0, data: { total: 0, list: [{ id: "string", name: "string", price: 0 }] } },
    updatedAt: Date.now(),
  },
  {
    id: "1005",
    title: "更新购物车",
    method: "PUT",
    path: "/api/cart/{cartId}/items",
    catName: "购物车",
    reqParams: [{ name: "cartId", type: "string", required: true, desc: "购物车 ID" }],
    reqQuery: [],
    reqHeaders: [{ name: "Authorization", type: "string", required: true, desc: "Bearer Token" }],
    reqBodyType: "json",
    reqBody: { skuId: "string", quantity: 1, selected: true },
    resBody: { code: 0, data: { cartId: "string", totalItems: 0, totalPrice: 0 } },
    updatedAt: Date.now(),
  },
];
