package com.lingce.aicleaner.settings

import com.intellij.credentialStore.CredentialAttributes
import com.intellij.credentialStore.Credentials
import com.intellij.credentialStore.generateServiceName
import com.intellij.ide.passwordSafe.PasswordSafe
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.util.xmlb.XmlSerializerUtil

/**
 * 插件全局设置。API Key 通过 [PasswordSafe] 安全存储，其余配置持久化到 XML。
 */
@State(
    name = "AiFileCleanerSettings",
    storages = [Storage("aiFileCleaner.xml")],
)
class AiCleanerSettings : PersistentStateComponent<AiCleanerSettings.State> {

    class State {
        // —— AI 接口配置 ——
        var baseUrl: String = "https://api.openai.com/v1"
        var model: String = "gpt-4o-mini"

        // —— 行为开关 ——
        /** 启用 AI 辅助判定（仅在本地规则不确定时调用）。 */
        var enableAi: Boolean = true

        /** 监听新导入/新建文件并自动分类提示。 */
        var watchImportedFiles: Boolean = true

        /**
         * 自动执行清理（删除 tmp / AI 无用文件、忽略配置文件）。
         * 关闭时仅弹通知，由用户手动确认；开启时静默执行（可疑文件永远不会被自动删除）。
         */
        var autoClean: Boolean = false

        /** 删除前先转存到隔离目录（更安全）。 */
        var deleteToQuarantine: Boolean = true

        // —— 隔离目录 ——
        /** 隔离/转存目录。为空时默认使用 <项目根>/.ai-cleaner-quarantine 。 */
        var quarantineDir: String = ""

        // —— 自定义规则（换行/逗号分隔的 glob，大小写不敏感）——
        var tmpPatterns: String = DEFAULT_TMP_PATTERNS
        var aiConfigPatterns: String = DEFAULT_AI_CONFIG_PATTERNS
        var projectConfigPatterns: String = DEFAULT_PROJECT_CONFIG_PATTERNS
        var aiGeneratedNamePatterns: String = DEFAULT_AI_GENERATED_NAME_PATTERNS

        /** 内容中出现这些标记则判定为 AI 生成（换行分隔，大小写不敏感）。 */
        var aiContentMarkers: String = DEFAULT_AI_CONTENT_MARKERS
    }

    private var myState = State()

    override fun getState(): State = myState

    override fun loadState(state: State) {
        XmlSerializerUtil.copyBean(state, myState)
    }

    // ——— API Key 安全存取 ———

    var apiKey: String
        get() = PasswordSafe.instance.getPassword(credentialAttributes()) ?: ""
        set(value) {
            PasswordSafe.instance.set(credentialAttributes(), Credentials(KEY_USER, value))
        }

    val isAiConfigured: Boolean
        get() = myState.enableAi &&
            myState.baseUrl.isNotBlank() &&
            apiKey.isNotBlank()

    private fun credentialAttributes(): CredentialAttributes =
        CredentialAttributes(generateServiceName("AiFileCleaner", KEY_USER))

    companion object {
        private const val KEY_USER = "ai-file-cleaner-api-key"

        fun getInstance(): AiCleanerSettings =
            ApplicationManager.getApplication().getService(AiCleanerSettings::class.java)

        const val DEFAULT_TMP_PATTERNS =
            "*.tmp, *.temp, *.bak, *.old, *.orig, *.rej, *.swp, *.swo, *.swn, *.cache, " +
                "*~, *.pyc, *.pyo, *.class, *.log, *.pid, .DS_Store, Thumbs.db, desktop.ini, " +
                "*.hprof, hs_err_pid*.log, npm-debug.log*, yarn-error.log*, *.tsbuildinfo, *.stackdump"

        const val DEFAULT_AI_CONFIG_PATTERNS =
            ".cursor, .cursorrules, .cursorignore, .cursor/**, " +
                ".aider*, .aider.conf.yml, .aider.chat.history.md, .aider.tags.cache*, " +
                "CLAUDE.md, CLAUDE.local.md, .claude, .claude/**, AGENTS.md, " +
                ".continue, .continue/**, .codeium, .codeium/**, .windsurfrules, .windsurf, .windsurf/**, " +
                ".github/copilot-instructions.md, .roo, .roo/**, .cline*, .gemini, .gemini/**, " +
                ".ai, .ai/**, .gptignore"

        const val DEFAULT_PROJECT_CONFIG_PATTERNS =
            ".editorconfig, .prettierrc*, .prettierignore, .eslintrc*, .eslintignore, " +
                ".babelrc*, .npmrc, .nvmrc, .browserslistrc, .stylelintrc*, " +
                "jsconfig.json, .gitattributes, .gitmessage"

        const val DEFAULT_AI_GENERATED_NAME_PATTERNS =
            "scratch_*, scratch.*, untitled*, temp_*, tmp_*, demo_*, example_*, sample_*, " +
                "*.generated.*, *_generated.*, *.gen.*, test_temp_*, debug_*, foo.*, bar.*, " +
                "new_file*, copy_of_*, *_copy.*, *_ai.*, ai_*"

        const val DEFAULT_AI_CONTENT_MARKERS =
            "This file was generated by\n" +
                "auto-generated by\n" +
                "AI-generated\n" +
                "Generated by AI\n" +
                "Generated by ChatGPT\n" +
                "Generated by Claude\n" +
                "Generated by Copilot\n" +
                "Generated by Cursor\n" +
                "@generated\n" +
                "DO NOT EDIT THIS FILE\n" +
                "Co-authored-by: Cursor\n" +
                "Co-authored-by: GitHub Copilot"
    }
}
