package com.lingce.cleanguard.detection

import com.intellij.openapi.vfs.VirtualFile
import com.lingce.cleanguard.model.ClassifiedFile
import com.lingce.cleanguard.model.FileCategory
import java.nio.charset.StandardCharsets
import java.util.Locale

object FileClassifier {

    private val TMP_EXTENSIONS = setOf(
        "tmp", "temp", "swp", "swo", "bak", "old", "orig", "save",
    )

    private val TMP_NAMES = setOf(
        ".ds_store", "thumbs.db", "desktop.ini", ".directory",
    )

    private val AI_CONFIG_PATTERNS = listOf(
        Regex("""^\.cursor(/|$)"""),
        Regex("""^\.copilot(/|$)"""),
        Regex("""^\.continue(/|$)"""),
        Regex("""^\.windsurf(/|$)"""),
        Regex("""^\.aider(\.|$)"""),
        Regex("""^\.codeium(/|$)"""),
        Regex("""^\.tabnine(/|$)"""),
        Regex("""^\.cursorrules$""", RegexOption.IGNORE_CASE),
        Regex("""^agents\.md$""", RegexOption.IGNORE_CASE),
        Regex("""^\.cursorignore$""", RegexOption.IGNORE_CASE),
        Regex("""^\.cursorindexingignore$""", RegexOption.IGNORE_CASE),
        Regex("""^clean-guard\.xml$""", RegexOption.IGNORE_CASE),
    )

    private val PROJECT_CONFIG_PATTERNS = listOf(
        Regex("""^\.env(\..+)?$"""),
        Regex("""^local\.properties$"""),
        Regex("""^\.idea/workspace\.xml$"""),
        Regex("""^\.idea/shelf(/|$)"""),
        Regex("""^\.vscode/launch\.json$"""),
        Regex("""^\.vscode/settings\.json$"""),
        Regex("""^secrets?\.(ya?ml|json|properties)$""", RegexOption.IGNORE_CASE),
        Regex("""^\.clean-guard(/|$)"""),
    )

    private val AI_GENERATED_MARKERS = listOf(
        "generated by ai",
        "generated by chatgpt",
        "generated by copilot",
        "generated by cursor",
        "auto-generated by",
        "this file was generated",
        "do not edit manually",
        "cursor agent",
        "ai-generated",
        "written by an ai",
        "<!-- ai -->",
        "// ai generated",
        "/* ai generated */",
    )

    private val SUSPICIOUS_NAME_PATTERNS = listOf(
        Regex("""^[a-f0-9]{32,}$""", RegexOption.IGNORE_CASE),
        Regex("""^tmp[_-].*""", RegexOption.IGNORE_CASE),
        Regex("""^untitled\d*$""", RegexOption.IGNORE_CASE),
        Regex("""^copy of .*""", RegexOption.IGNORE_CASE),
        Regex("""^\d{10,}\.(txt|log|json)$"""),
        Regex("""^~\$.*"""),
    )

    fun classify(file: VirtualFile, projectRelativePath: String): ClassifiedFile {
        if (file.isDirectory) {
            return classifyDirectory(projectRelativePath)
        }
        return classifyFile(file, projectRelativePath)
    }

    private fun classifyDirectory(relativePath: String): ClassifiedFile {
        val normalized = normalizePath(relativePath)
        AI_CONFIG_PATTERNS.firstOrNull { it.containsMatchIn(normalized) }?.let {
            return ClassifiedFile(normalized, FileCategory.AI_CONFIG, "AI 工具配置目录")
        }
        PROJECT_CONFIG_PATTERNS.firstOrNull { it.containsMatchIn(normalized) }?.let {
            return ClassifiedFile(normalized, FileCategory.PROJECT_CONFIG, "项目本地配置目录")
        }
        return ClassifiedFile(normalized, FileCategory.SAFE, "目录")
    }

    private fun classifyFile(file: VirtualFile, relativePath: String): ClassifiedFile {
        val normalized = normalizePath(relativePath)
        val name = file.name
        val nameLower = name.lowercase(Locale.getDefault())
        val ext = name.substringAfterLast('.', "").lowercase(Locale.getDefault())

        if (name.endsWith("~") || nameLower in TMP_NAMES || ext in TMP_EXTENSIONS) {
            return ClassifiedFile(normalized, FileCategory.TMP, "临时/备份文件")
        }

        AI_CONFIG_PATTERNS.firstOrNull { it.containsMatchIn(normalized) }?.let {
            return ClassifiedFile(normalized, FileCategory.AI_CONFIG, "AI 工具配置文件")
        }

        PROJECT_CONFIG_PATTERNS.firstOrNull { it.containsMatchIn(normalized) }?.let {
            return ClassifiedFile(normalized, FileCategory.PROJECT_CONFIG, "项目本地配置文件")
        }

        if (SUSPICIOUS_NAME_PATTERNS.any { it.matches(name) }) {
            return ClassifiedFile(normalized, FileCategory.SUSPICIOUS, "文件名可疑")
        }

        val contentHint = readContentHint(file)
        if (contentHint != null && AI_GENERATED_MARKERS.any { contentHint.contains(it) }) {
            return ClassifiedFile(normalized, FileCategory.AI_GENERATED_USELESS, "内容含 AI 生成标记", 0.85)
        }

        if (contentHint != null && looksLikeAiScaffold(contentHint)) {
            return ClassifiedFile(normalized, FileCategory.AI_GENERATED_USELESS, "疑似 AI 脚手架/占位内容", 0.7)
        }

        if (nameLower.startsWith("cursor_") || nameLower.contains("_ai_")) {
            return ClassifiedFile(normalized, FileCategory.SUSPICIOUS, "文件名暗示 AI 来源", 0.6)
        }

        return ClassifiedFile(normalized, FileCategory.UNKNOWN, "待进一步检测")
    }

    private fun looksLikeAiScaffold(content: String): Boolean {
        val trimmed = content.trim()
        if (trimmed.length < 20) return false
        val placeholderLines = listOf(
            "todo: implement",
            "your code here",
            "add your code",
            "placeholder",
            "lorem ipsum",
            "example.com",
            "foo bar",
        )
        val lower = trimmed.lowercase(Locale.getDefault())
        val hits = placeholderLines.count { lower.contains(it) }
        return hits >= 2 && trimmed.lines().size <= 30
    }

    fun readContentHint(file: VirtualFile): String? {
        if (file.length <= 0 || file.length > 512_000) return null
        return try {
            String(file.contentsToByteArray(), StandardCharsets.UTF_8)
                .lowercase(Locale.getDefault())
                .take(4096)
        } catch (_: Exception) {
            null
        }
    }

    fun normalizePath(path: String): String =
        path.replace('\\', '/').trim('/')

    fun isUnderIgnoredVcs(file: VirtualFile): Boolean {
        var current: VirtualFile? = file
        while (current != null) {
            if (current.name == ".git" || current.name == "node_modules" || current.name == "build") {
                return true
            }
            current = current.parent
        }
        return false
    }
}
