package com.aifileguard.classify

import com.aifileguard.model.FileCategory
import com.aifileguard.model.FileVerdict
import com.aifileguard.model.SuggestedAction
import com.aifileguard.settings.AiGuardSettings
import com.google.gson.Gson
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import com.intellij.openapi.diagnostic.logger
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration

/**
 * Classifies a file using an OpenAI-compatible chat completion endpoint.
 * Used only for files that local rules could not classify confidently.
 */
class AiClassifier(private val settings: AiGuardSettings.State) {

    private val gson = Gson()
    private val http: HttpClient = HttpClient.newBuilder()
        .connectTimeout(Duration.ofSeconds(15))
        .build()

    fun isConfigured(): Boolean = settings.enableAi && settings.apiKey.isNotBlank() && settings.baseUrl.isNotBlank()

    /**
     * @return an updated verdict, or [base] unchanged if the AI call failed.
     */
    fun classify(base: FileVerdict, contentSnippet: String): FileVerdict {
        if (!isConfigured()) return base
        return try {
            val body = buildRequestBody(base, contentSnippet)
            val request = HttpRequest.newBuilder()
                .uri(URI.create(chatCompletionsUrl()))
                .timeout(Duration.ofSeconds(45))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer ${settings.apiKey}")
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .build()

            val response = http.send(request, HttpResponse.BodyHandlers.ofString())
            if (response.statusCode() / 100 != 2) {
                LOG.warn("AI classify HTTP ${response.statusCode()}: ${response.body().take(300)}")
                return base
            }
            parseResponse(base, response.body())
        } catch (t: Throwable) {
            LOG.warn("AI classify failed for ${base.relativePath}: ${t.message}")
            base
        }
    }

    private fun chatCompletionsUrl(): String {
        val trimmed = settings.baseUrl.trimEnd('/')
        return if (trimmed.endsWith("/chat/completions")) trimmed else "$trimmed/chat/completions"
    }

    private fun buildRequestBody(base: FileVerdict, contentSnippet: String): String {
        val system = """
            You are a meticulous workspace-hygiene assistant embedded in an IDE.
            Classify a single file and recommend an action so the workspace stays clean.
            Categories:
              - AI_GENERATED_USELESS: throwaway content generated by an AI assistant with no lasting value.
              - TEMPORARY: temp/cache/build leftovers.
              - PROJECT_CONFIG: real project configuration that must be kept but ignored by VCS.
              - AI_CONFIG: configuration for AI assistants/tools (keep but ignore).
              - SUSPICIOUS: unexpected/unknown; a human should decide.
              - NORMAL: genuine source/asset; keep it.
            Actions: DELETE, ADD_TO_IGNORE, QUARANTINE, KEEP.
            Respond with ONLY a compact JSON object:
            {"category":"...","action":"...","confidence":0.0,"reason":"short reason"}
        """.trimIndent()

        val user = buildString {
            append("Relative path: ").append(base.relativePath).append('\n')
            append("Size (bytes): ").append(base.sizeBytes).append('\n')
            append("Local rule guess: ").append(base.category.name).append('\n')
            append("--- content snippet (may be truncated) ---\n")
            append(contentSnippet)
        }

        val payload = JsonObject().apply {
            addProperty("model", settings.model)
            addProperty("temperature", 0.0)
            add("messages", gson.toJsonTree(
                listOf(
                    mapOf("role" to "system", "content" to system),
                    mapOf("role" to "user", "content" to user),
                )
            ))
        }
        return gson.toJson(payload)
    }

    private fun parseResponse(base: FileVerdict, raw: String): FileVerdict {
        val root = JsonParser.parseString(raw).asJsonObject
        val content = root.getAsJsonArray("choices")
            ?.firstOrNull()?.asJsonObject
            ?.getAsJsonObject("message")
            ?.get("content")?.asString
            ?: return base

        val json = extractJsonObject(content) ?: return base
        val category = json.get("category")?.asString?.let { runCatching { FileCategory.valueOf(it) }.getOrNull() }
            ?: base.category
        val action = json.get("action")?.asString?.let { runCatching { SuggestedAction.valueOf(it) }.getOrNull() }
            ?: defaultActionFor(category)
        val confidence = json.get("confidence")?.let { runCatching { it.asDouble }.getOrNull() } ?: 0.6
        val reason = json.get("reason")?.asString ?: "AI classification"

        return base.copy(
            category = category,
            action = action,
            reason = reason,
            confidence = confidence.coerceIn(0.0, 1.0),
            byAi = true,
        )
    }

    private fun defaultActionFor(category: FileCategory): SuggestedAction = when (category) {
        FileCategory.AI_GENERATED_USELESS, FileCategory.TEMPORARY -> SuggestedAction.DELETE
        FileCategory.PROJECT_CONFIG, FileCategory.AI_CONFIG -> SuggestedAction.ADD_TO_IGNORE
        FileCategory.SUSPICIOUS -> SuggestedAction.QUARANTINE
        FileCategory.NORMAL -> SuggestedAction.KEEP
    }

    private fun extractJsonObject(text: String): JsonObject? {
        val start = text.indexOf('{')
        val end = text.lastIndexOf('}')
        if (start < 0 || end <= start) return null
        return runCatching { JsonParser.parseString(text.substring(start, end + 1)).asJsonObject }.getOrNull()
    }

    companion object {
        private val LOG = logger<AiClassifier>()
    }
}
